### ISSUE TITLE
Frozen binary: chat and splash both crash (regressed by #387)

### ISSUE THREAD

**Issue by tobocop2** [tobocop2/lilbee#410]
The shipped compiled binaries (b502/b503) are broken in two ways:

- **Chat crashes** on the first message with `ValueError: bad value(s) in fds_to_keep`. The multiprocessing resource tracker fails to spawn under the TUI because its early warm-up was disabled in frozen builds.
- **Splash crashes** with `AttributeError: nuitka_module_loader has no attribute 'get_code'`. The splash child process was launched in a way Nuitka's module loader doesn't support.

Both are regressions from #387. Fixed in #408, shipping in v0.6.66b504. The release smoke test was also tightened so a frozen-binary reinvocation that raises now fails CI instead of reaching users.

**Comment by tobocop2** [comment]
Fixed by #408 and shipped in v0.6.66b504, now live as the latest release (PyPI, Homebrew, AUR, Nix, snap, flatpak, scoop, Docker, and CUDA packages all published). The frozen-binary chat and splash crashes are resolved.
